In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\kashi\OneDrive\图片\Desktop\techcadd\workliifeballance dataset.zip")
df.head()

,id,gender,occupation_type,avg_work_hours_per_day,avg_rest_hours_per_day,avg_sleep_hours_per_day,avg_exercise_hours_per_day,age_at_death
0,10001,Female,Teacher,6.60,10.92,5.38,1.10,88
1,10002,Male,Office Worker,9.65,7.65,6.31,0.39,76
2,10003,Female,Manager,13.77,1.00,8.02,1.21,78
3,10004,Female,Freelancer,10.94,5.18,7.59,0.29,74
4,10005,Male,Engineer,9.81,5.11,7.38,1.70,78

In [3]:
df.shape

(10000, 8)

In [4]:
df.describe

<bound method NDFrame.describe of          id  gender occupation_type  avg_work_hours_per_day  \
0     10001  Female         Teacher                    6.60
1     10002    Male   Office Worker                    9.65
2     10003  Female         Manager                   13.77
3     10004  Female      Freelancer                   10.94
4     10005    Male        Engineer                    9.81
...     ...     ...             ...                     ...
9995  19996  Female      Technician                    8.39
9996  19997    Male   Retail Worker                    9.58
9997  19998  Female      Consultant                   10.02
9998  19999  Female        Engineer                    7.97
9999  20000  Female      Freelancer                    7.73

      avg_rest_hours_per_day  avg_sleep_hours_per_day  \
0                      10.92                     5.38
1                       7.65                     6.31
2                       1.00                     8.02
3                       5.18                     7.59
4                       5.11                     7.38
...                      ...                      ...
9995                    8.12                     6.91
9996                    6.40                     6.93
9997                    4.75                     7.55
9998                    8.07                     7.78
9999                    7.66                     7.61

      avg_exercise_hours_per_day  age_at_death
0                           1.10            88
1                           0.39            76
2                           1.21            78
3                           0.29            74
4                           1.70            78
...                          ...           ...
9995                        0.58            89
9996                        1.09            90
9997                        1.68            89
9998                        0.17            87
9999                        1.00            87

[10000 rows x 8 columns]>

In [5]:
df.isna().sum()

id                            0
gender                        0
occupation_type               0
avg_work_hours_per_day        0
avg_rest_hours_per_day        0
avg_sleep_hours_per_day       0
avg_exercise_hours_per_day    0
age_at_death                  0
dtype: int64

In [6]:
df.columns

Index(['id', 'gender', 'occupation_type', 'avg_work_hours_per_day',
       'avg_rest_hours_per_day', 'avg_sleep_hours_per_day',
       'avg_exercise_hours_per_day', 'age_at_death'],
      dtype='object')

In [7]:
x = df[["id",'gender','occupation_type','avg_work_hours_per_day','avg_rest_hours_per_day','avg_sleep_hours_per_day','avg_exercise_hours_per_day',]]
x.head()

,id,gender,occupation_type,avg_work_hours_per_day,avg_rest_hours_per_day,avg_sleep_hours_per_day,avg_exercise_hours_per_day
0,10001,Female,Teacher,6.60,10.92,5.38,1.10
1,10002,Male,Office Worker,9.65,7.65,6.31,0.39
2,10003,Female,Manager,13.77,1.00,8.02,1.21
3,10004,Female,Freelancer,10.94,5.18,7.59,0.29
4,10005,Male,Engineer,9.81,5.11,7.38,1.70

In [8]:
y = df['age_at_death']

In [9]:
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree=3)
x_poly=pf.fit_transform(x)

ValueError: could not convert string to float: 'Female'

In [10]:
from sklearn.preprocessing import LabelEncoder
LE= LabelEncoder()
x['gender']=LE.fit_transform(x['gender'])
x['occupation_type'] = LE.fit_transform(x["occupation_type"])

C:\Users\kashi\AppData\Local\Temp\ipykernel_25392\3492828079.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['gender']=LE.fit_transform(x['gender'])
C:\Users\kashi\AppData\Local\Temp\ipykernel_25392\3492828079.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['occupation_type'] = LE.fit_transform(x["occupation_type"])

In [11]:
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree=3)
x_poly=pf.fit_transform(x)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_poly,y,train_size=0.8,random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [ ]:
lr.fit(x_train,y_train)

In [ ]:
prediction =lr.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,prediction)