In [1]:
import pandas as pd

In [2]:
dt= pd.read_csv(r"C:\Users\kashi\OneDrive\图片\Desktop\techcadd\student peforrmencev datadet.zip")
dt.head()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [3]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dt['placement_status']=le.fit_transform(dt['placement_status'])
dt

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,1
1,4,69,5,3,8,56,100.00,1
2,11,60,7,6,10,45,100.00,1
3,8,99,9,8,4,55,90.17,1
4,5,52,8,6,8,40,78.82,1
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,0
9996,7,98,6,9,4,87,100.00,1
9997,10,44,8,5,10,37,95.94,1
9998,10,75,7,5,8,52,88.61,1
9999,2,70,6,11,16,52,78.96,1

In [4]:
x=dt.drop(columns=['placement_status'])
x

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
0,7,56,8,7,10,62,100.00
1,4,69,5,3,8,56,100.00
2,11,60,7,6,10,45,100.00
3,8,99,9,8,4,55,90.17
4,5,52,8,6,8,40,78.82
...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31
9996,7,98,6,9,4,87,100.00
9997,10,44,8,5,10,37,95.94
9998,10,75,7,5,8,52,88.61
9999,2,70,6,11,16,52,78.96

In [5]:
y=dt['placement_status']
y

0       1
1       1
2       1
3       1
4       1
       ..
9995    0
9996    1
9997    1
9998    1
9999    1
Name: placement_status, Length: 10000, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.75,random_state=42)

In [20]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor(max_depth=2)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor(max_depth=5,n_estimators=10)

In [21]:
dtr.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=2)

In [22]:
prediction=dtr.predict(x_test)

In [23]:
from sklearn.metrics import r2_score
r2_score(y_test,prediction)*100

100.0