In [21]:
import pandas as pd

In [22]:
df  = pd.read_csv(r"C:\Users\kashi\OneDrive\图片\Desktop\techcadd\bmw_global_sales_dataset.csv")
df.head()

,year,month,country,model,segment,engine_type,price_usd,marketing_spend_usd,dealership_count,fuel_price_usd,gdp_growth_percent,interest_rate_percent,competition_index,units_sold
0,2021,1,Australia,X1,SUV,Petrol,82234,315372,96,0.97,6.29,1.2,8,324
1,2018,8,Australia,i4,Sedan,Electric,82291,447798,234,0.97,6.29,1.2,7,556
2,2022,12,USA,5 Series,Electric,Hybrid,40594,259755,25,0.97,6.29,1.2,7,152
3,2019,11,Australia,i7,SUV,Electric,42371,323541,319,0.97,6.29,1.2,5,730
4,2021,12,Brazil,X5,SUV,Diesel,82315,482015,367,0.97,6.29,1.2,2,1156

In [23]:
df.isna().sum()

year                     0
month                    0
country                  0
model                    0
segment                  0
engine_type              0
price_usd                0
marketing_spend_usd      0
dealership_count         0
fuel_price_usd           0
gdp_growth_percent       0
interest_rate_percent    0
competition_index        0
units_sold               0
dtype: int64

In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['country'] = le.fit_transform(df['country'])
df['country'] = le.fit_transform(df['country'])
df['model'] = le.fit_transform(df['model'])
df['segment'] = le.fit_transform(df['segment'])
df['engine_type'] = le.fit_transform(df['engine_type'])
df.head()

,year,month,country,model,segment,engine_type,price_usd,marketing_spend_usd,dealership_count,fuel_price_usd,gdp_growth_percent,interest_rate_percent,competition_index,units_sold
0,2021,1,0,3,1,3,82234,315372,96,0.97,6.29,1.2,8,324
1,2018,8,0,7,2,1,82291,447798,234,0.97,6.29,1.2,7,556
2,2022,12,9,1,0,2,40594,259755,25,0.97,6.29,1.2,7,152
3,2019,11,0,8,1,1,42371,323541,319,0.97,6.29,1.2,5,730
4,2021,12,1,5,1,0,82315,482015,367,0.97,6.29,1.2,2,1156

In [25]:
x =df[['year','month','country','model','segment','engine_type','price_usd','marketing_spend_usd','dealership_count']]
x.head()

,year,month,country,model,segment,engine_type,price_usd,marketing_spend_usd,dealership_count
0,2021,1,0,3,1,3,82234,315372,96
1,2018,8,0,7,2,1,82291,447798,234
2,2022,12,9,1,0,2,40594,259755,25
3,2019,11,0,8,1,1,42371,323541,319
4,2021,12,1,5,1,0,82315,482015,367

In [26]:
y =df['fuel_price_usd']

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)

In [29]:
x.dtypes

year                   int64
month                  int64
country                int64
model                  int64
segment                int64
engine_type            int64
price_usd              int64
marketing_spend_usd    int64
dealership_count       int64
dtype: object

In [44]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [45]:
lr.fit(x_train,y_train)

LinearRegression()

In [46]:
prediction=lr.predict(x_test)
from sklearn.metrics import r2_score
r2_score(y_test,prediction)*100

100.0

### polynomial regression

In [47]:
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree=3)
pf_poly = pf.fit_transform(x)
pf

PolynomialFeatures(degree=3)

In [48]:
pre = lr.predict(x_test)

In [49]:
from sklearn.metrics import r2_score
r2_score(pre,y_test)

1.0

### decision tree

In [85]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8)

In [90]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor(max_depth=5,random_state=42)

In [91]:
dt.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=5, random_state=42)

In [92]:
pre = dt.predict(x_test)

In [93]:
from sklearn.metrics import r2_score
r2_score(y_test,pre)

0.0

## Random forest

In [ ]:
from sklearn.model_selection import train_test_split

In [40]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(max_depth=7,n_estimators=12)

In [41]:
rf.fit(x_train,y_train)

RandomForestRegressor(max_depth=7, n_estimators=12)

In [42]:
prediction = rf.predict(x_test)
from sklearn.metrics import r2_score
r2_score(y_test,prediction)*100

0.0