In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\kashi\OneDrive\图片\Desktop\techcadd\chocolate_sales_2025_dataset.csv')
df.head()

,Sale_ID,Date,Brand,Product_Type,Country,Sales_Channel,Payment_Method,Price_USD,Units_Sold,Revenue_USD
0,1,2025-11-24,Cadbury,Milk Chocolate,France,Supermarket,Digital Wallet,5.00,194,970.00
1,2,2025-02-22,Lindt,Chocolate Bar,India,Online,Cash,17.73,144,2553.12
2,3,2025-02-17,Toblerone,Dark Chocolate,Australia,Supermarket,Digital Wallet,7.42,134,994.28
3,4,2025-11-29,Ferrero,Truffles,Italy,Convenience Store,Cash,18.28,112,2047.36
4,5,2025-03-23,Cadbury,Milk Chocolate,France,Convenience Store,Cash,18.21,92,1675.32

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [11]:
df['Brand'] = le.fit_transform(df['Brand'])
df['Country'] = le.fit_transform(df['Country'])
df['Sales_Channel'] = le.fit_transform(df['Sales_Channel'])
df['Payment_Method'] = le.fit_transform(df['Payment_Method'])
#pd.get_dummies(df,columns=['Product_Type','Country','Sales_Channel','Payment_Method'])
df['Payment_Method']

0      2
1      1
2      2
3      1
4      1
      ..
495    2
496    1
497    0
498    1
499    1
Name: Payment_Method, Length: 500, dtype: int64

In [13]:
x = df.drop(columns='Revenue_USD')
x

,Sale_ID,Date,Brand,Product_Type,Country,Sales_Channel,Payment_Method,Price_USD,Units_Sold
0,1,2025-11-24,0,Milk Chocolate,2,3,2,5.00,194
1,2,2025-02-22,3,Chocolate Bar,4,1,1,17.73,144
2,3,2025-02-17,6,Dark Chocolate,0,3,2,7.42,134
3,4,2025-11-29,1,Truffles,5,0,1,18.28,112
4,5,2025-03-23,0,Milk Chocolate,2,0,1,18.21,92
...,...,...,...,...,...,...,...,...,...
495,496,2025-08-11,0,Milk Chocolate,2,2,2,6.03,30
496,497,2025-10-11,6,White Chocolate,7,0,1,18.75,191
497,498,2025-02-19,6,Truffles,3,1,0,3.62,151
498,499,2025-01-02,5,Chocolate Box,5,2,1,12.12,80
499,500,2025-02-19,4,White Chocolate,8,2,1,3.08,48

In [14]:
y = df[['Revenue_USD']]