In [46]:
import pandas as pd

In [63]:
df = pd.read_csv(r'C:\Users\kashi\OneDrive\图片\Desktop\techcadd\chocolate_sales_2025_dataset.csv')
df.head()

,Sale_ID,Date,Brand,Product_Type,Country,Sales_Channel,Payment_Method,Price_USD,Units_Sold,Revenue_USD
0,1,2025-11-24,Cadbury,Milk Chocolate,France,Supermarket,Digital Wallet,5.00,194,970.00
1,2,2025-02-22,Lindt,Chocolate Bar,India,Online,Cash,17.73,144,2553.12
2,3,2025-02-17,Toblerone,Dark Chocolate,Australia,Supermarket,Digital Wallet,7.42,134,994.28
3,4,2025-11-29,Ferrero,Truffles,Italy,Convenience Store,Cash,18.28,112,2047.36
4,5,2025-03-23,Cadbury,Milk Chocolate,France,Convenience Store,Cash,18.21,92,1675.32

In [48]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [49]:
df['Brand'] = le.fit_transform(df['Brand'])
df['Country'] = le.fit_transform(df['Country'])
df['Sales_Channel'] = le.fit_transform(df['Sales_Channel'])
df['Payment_Method'] = le.fit_transform(df['Payment_Method'])
#pd.get_dummies(df,columns=['Product_Type','Country','Sales_Channel','Payment_Method'])
df['Payment_Method']

0      2
1      1
2      2
3      1
4      1
      ..
495    2
496    1
497    0
498    1
499    1
Name: Payment_Method, Length: 500, dtype: int64

In [50]:
x = df.drop(columns='Revenue_USD')
x

,Sale_ID,Date,Brand,Product_Type,Country,Sales_Channel,Payment_Method,Price_USD,Units_Sold
0,1,2025-11-24,0,Milk Chocolate,2,3,2,5.00,194
1,2,2025-02-22,3,Chocolate Bar,4,1,1,17.73,144
2,3,2025-02-17,6,Dark Chocolate,0,3,2,7.42,134
3,4,2025-11-29,1,Truffles,5,0,1,18.28,112
4,5,2025-03-23,0,Milk Chocolate,2,0,1,18.21,92
...,...,...,...,...,...,...,...,...,...
495,496,2025-08-11,0,Milk Chocolate,2,2,2,6.03,30
496,497,2025-10-11,6,White Chocolate,7,0,1,18.75,191
497,498,2025-02-19,6,Truffles,3,1,0,3.62,151
498,499,2025-01-02,5,Chocolate Box,5,2,1,12.12,80
499,500,2025-02-19,4,White Chocolate,8,2,1,3.08,48

In [51]:
y = df[['Revenue_USD']]

In [87]:
df.drop(columns='Date')

,Sale_ID,Brand,Product_Type,Country,Sales_Channel,Payment_Method,Price_USD,Units_Sold,Revenue_USD
0,1,Cadbury,Milk Chocolate,France,Supermarket,Digital Wallet,5.00,194,970.00
2,4,Ferrero,Truffles,Italy,Convenience Store,Cash,18.28,112,2047.36
3,5,Cadbury,Milk Chocolate,France,Convenience Store,Cash,18.21,92,1675.32
4,6,Nestle,White Chocolate,Italy,Convenience Store,Cash,11.05,96,1060.80
5,7,Lindt,Chocolate Bar,UAE,Convenience Store,Digital Wallet,14.57,101,1471.57
...,...,...,...,...,...,...,...,...,...
492,496,Cadbury,Milk Chocolate,France,Specialty Store,Digital Wallet,6.03,30,180.90
493,497,Toblerone,White Chocolate,UAE,Convenience Store,Cash,18.75,191,3581.25
494,498,Toblerone,Truffles,Germany,Online,Card,3.62,151,546.62
495,499,Nestle,Chocolate Box,Italy,Specialty Store,Cash,12.12,80,969.60
496,500,Mars,White Chocolate,UK,Specialty Store,Cash,3.08,48,147.84

In [88]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [89]:
df['Date'].apply(type).value_counts()

Date
<class 'str'>    494
Name: count, dtype: int64

In [90]:
df[df['Date']=='2025-11-24'].value_counts()

Sale_ID  Date        Brand      Product_Type    Country       Sales_Channel  Payment_Method  Price_USD  Units_Sold  Revenue_USD
1        2025-11-24  Cadbury    Milk Chocolate  France        Supermarket    Digital Wallet  5.00       194         970.0          1
198      2025-11-24  Hershey    Dark Chocolate  Saudi Arabia  Supermarket    Digital Wallet  11.90      34          404.6          1
394      2025-11-24  Toblerone  Truffles        Italy         Online         Card            9.55       104         993.2          1
Name: count, dtype: int64

In [91]:
df.drop([1,198,394],inplace=True)

KeyError: '[1, 198, 394] not found in axis'

In [92]:
df.reset_index(drop=True,inplace=True)

In [104]:
df['Date']=pd.to_datetime(df['Date'],errors='coerce')
df['Date']
df['Date'].dtype

dtype('<M8[ns]')

In [105]:
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree=3)
x_poly = pf.fit_transform(x)

ValueError: could not convert string to float: '2025-11-24'

In [106]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_poly,y,test_size=0.2)

NameError: name 'x_poly' is not defined

In [61]:
for col in df.columns:
    print(col,df[col].apply(type).value_counts())

Sale_ID Sale_ID
<class 'int'>    500
Name: count, dtype: int64
Brand Brand
<class 'int'>    500
Name: count, dtype: int64
Product_Type Product_Type
<class 'str'>    500
Name: count, dtype: int64
Country Country
<class 'int'>    500
Name: count, dtype: int64
Sales_Channel Sales_Channel
<class 'int'>    500
Name: count, dtype: int64
Payment_Method Payment_Method
<class 'int'>    500
Name: count, dtype: int64
Price_USD Price_USD
<class 'float'>    500
Name: count, dtype: int64
Units_Sold Units_Sold
<class 'int'>    500
Name: count, dtype: int64
Revenue_USD Revenue_USD
<class 'float'>    500
Name: count, dtype: int64