In [60]:
import pandas as pd

In [61]:
df = pd.read_csv(r"C:\Users\kashi\OneDrive\图片\Desktop\techcadd\chocolate_sales_2025_dataset.csv")
df.head()

,Sale_ID,Date,Brand,Product_Type,Country,Sales_Channel,Payment_Method,Price_USD,Units_Sold,Revenue_USD
0,1,2025-11-24,Cadbury,Milk Chocolate,France,Supermarket,Digital Wallet,5.00,194,970.00
1,2,2025-02-22,Lindt,Chocolate Bar,India,Online,Cash,17.73,144,2553.12
2,3,2025-02-17,Toblerone,Dark Chocolate,Australia,Supermarket,Digital Wallet,7.42,134,994.28
3,4,2025-11-29,Ferrero,Truffles,Italy,Convenience Store,Cash,18.28,112,2047.36
4,5,2025-03-23,Cadbury,Milk Chocolate,France,Convenience Store,Cash,18.21,92,1675.32

In [62]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [63]:
df['Brand'] = le.fit_transform(df['Brand'])
df['Product_Type']=le.fit_transform(df['Product_Type'])
df['Country'] = le.fit_transform(df['Country'])
df['Sales_Channel'] = le.fit_transform(df['Sales_Channel'])
df['Payment_Method'] = le.fit_transform(df['Payment_Method'])
df['Price_USD'] = le.fit_transform(df['Price_USD'])
df['Date'] = le.fit_transform(df['Date'])
df['Revenue_USD'] = le.fit_transform(df['Revenue_USD'])

In [64]:
df.isna().sum()

Sale_ID           0
Date              0
Brand             0
Product_Type      0
Country           0
Sales_Channel     0
Payment_Method    0
Price_USD         0
Units_Sold        0
Revenue_USD       0
dtype: int64

In [65]:
df.columns

Index(['Sale_ID', 'Date', 'Brand', 'Product_Type', 'Country', 'Sales_Channel',
       'Payment_Method', 'Price_USD', 'Units_Sold', 'Revenue_USD'],
      dtype='object')

In [66]:
x = df[['Sale_ID', 'Date', 'Brand', 'Product_Type', 'Country', 'Sales_Channel',
       'Price_USD', 'Revenue_USD','Units_Sold']]
x.head()

,Sale_ID,Date,Brand,Product_Type,Country,Sales_Channel,Price_USD,Revenue_USD,Units_Sold
0,1,246,0,3,2,3,48,201,194
1,2,43,3,0,4,1,309,410,144
2,3,38,6,2,0,3,94,205,134
3,4,251,1,4,5,0,320,368,112
4,5,65,0,3,2,0,318,327,92

In [67]:
y=df['Payment_Method']
y.head()

0    2
1    1
2    2
3    1
4    1
Name: Payment_Method, dtype: int64

In [68]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=42)

In [69]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [70]:
lr.fit(x_train,y_train)

c:\Users\kashi\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [71]:
pre = lr.predict(x_test)

In [72]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pre)*100

30.0

In [73]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=42)

In [74]:
from sklearn.ensemble import RandomForestClassifier
rc = RandomForestClassifier(max_depth=5,n_estimators=5)

In [75]:
rc.fit(x_train,y_train)

RandomForestClassifier(max_depth=5, n_estimators=5)

In [76]:
pre =rc.predict(x_test)

In [77]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pre)

0.25