In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\kashi\OneDrive\图片\Desktop\techcadd\loan_approval.csv")
df.head()

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False

In [ ]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()
df['name'] =le.fit_transform(df['name'])
df['city'] =le.fit_transform(df['city'])
df

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,46,326,113810,389,39698,27,50.0,False
1,218,989,44592,729,15446,28,55.0,False
2,1605,763,33278,584,11189,13,45.0,False
3,674,1793,127196,344,48823,29,50.0,False
4,1934,841,66048,496,47174,4,25.0,False
...,...,...,...,...,...,...,...,...
1995,772,1418,92163,770,12251,13,85.0,True
1996,548,981,38799,635,48259,17,40.0,False
1997,221,308,41957,763,16752,5,60.0,True
1998,804,2,139022,360,24031,35,55.0,False
1999,1496,1032,41188,482,31397,6,20.0,False

In [6]:
df.columns

Index(['name', 'city', 'income', 'credit_score', 'loan_amount',
       'years_employed', 'points', 'loan_approved'],
      dtype='object')

In [7]:
x =df[['name', 'city', 'income', 'credit_score', 'loan_amount',
       'years_employed', 'points']]

In [8]:
y =df['loan_approved']

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2,random_state=42)

In [10]:
from sklearn.tree import DecisionTreeClassifier
dc = DecisionTreeClassifier(max_depth=5)

In [11]:
dc.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=5)

In [13]:
pre = dc.predict(x_test)

In [15]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pre)*100

100.0